Add prettier, config options, and ADR
Open-SGF/gooddads pull request #86
Opened 2024-11-06 02:31 UTC by ntoombs19

2024-11-06 03:02 UTC, jason-klein commented
@ntoombs19 Please add the following to `.prettierignore` file and reverting your formatting changes to both of these files.

```
package-lock.json
composer.lock
```

When I search for configuring Prettier with Laravel projects, I found that a major community contributor recommends updating `.prettierignore` to include each of the following files to skip formatting upstream package files, generated files, etc.

```
node_modules
.env*
vendor/
/vendor
public/
.git
**/.git
```

I assume we are NOT using blade templates at all, since we're using Inertia.js + React? If that is NOT correct, be aware we can also configure Prettier to format JS inside the blade templates. Details below...

https://mattstauffer.com/blog/how-to-set-up-prettier-on-a-laravel-app-to-lint-tailwind-class-order-and-more/

2024-11-13 02:03 UTC, glitchedmob requested changes

2024-11-13 02:03 UTC, glitchedmob commented on .prettierrc
> +  "jsxSingleQuote": true,
Thoughts on changing this to `false`? I find using double quotes easier as it matches the patterns in Vanilla HTML and other frontend frameworks

2024-11-13 02:09 UTC, glitchedmob requested changes

2024-11-13 02:09 UTC, glitchedmob commented on .prettierrc
Can we change this to tabs instead of spaces?

2024-11-13 14:10 UTC, glitchedmob requested changes
Can add a Github action that runs `npm run prettier:check` to ensure we never merge code that doesn't match the formatting rules

2025-01-21 23:00 UTC, ntoombs19 commented on .prettierrc
> +  "jsxSingleQuote": true,
Changed to false

2025-01-21 23:00 UTC, ntoombs19 commented on .prettierrc
Done

2025-01-21 23:05 UTC, ntoombs19 commented
@glitchedmob I've resolved all PR feedback, resolved conflicts, and applied prettier formatting after merging in main from the upstream repo.

2025-01-22 00:18 UTC, glitchedmob approved these changes

2025-01-22 00:19 UTC, merged