Feature/permissions
Open-SGF/gooddads pull request #90
Opened 2024-12-10 21:32 UTC by ntoombs19

2025-01-12 20:48 UTC, kdebrecht requested changes
Great PR - I have a couple of suggestions here and a couple of examples of things you can use with inertia that may be helpful to know to make life easier moving forward.

2025-01-12 20:48 UTC, kdebrecht commented on app/Http/Resources/UserResource.php
> + */
In resources, we can easily reference properties by adding this at the top of the class to reference the model rather than explicitly defining each property.  Any changes to the model can get picked up and will be a lot easier to maintain resources


/**
 * @mixin \App\Models\User 
 */
class UserResource extends JsonResource

2025-01-12 20:48 UTC, kdebrecht commented on database/migrations/0001_01_01_000000_create_users_table.php
> +            $table->uuid('id')->primary()->unique();
The unique index on the primary key is redundant

$table->uuid('id')->primary()->unique();

2025-01-12 20:48 UTC, kdebrecht commented on database/migrations/2024_07_10_013407_create_permission_tables.php
> +            $table->uuid('uuid')->primary()->unique(); // permission id
I noticed that the model sets the key to UUI and we are defining here the id as uuid.

I would recommend that we just call this "id" rather than "id" so it is consistent with the other models so we dont have to remember what tables/models use uuid vs id
 
the fk references will need to be updated as well

2025-01-12 20:48 UTC, kdebrecht commented on database/migrations/2024_07_10_013407_create_permission_tables.php
> +            $table->uuid('uuid')->primary()->unique(); // role id
same recommendation here as well - the fk references will need to be updated as well

2025-01-12 20:48 UTC, kdebrecht commented on app/Http/Middleware/HandleInertiaRequests.php
> +      'auth.user' => fn() => $request->user()
Very good use of dot notation!  Really cleaned this up.. Good Stuff!

2025-01-12 20:48 UTC, kdebrecht commented on database/migrations/2024_07_10_013407_create_permission_tables.php
> +                ->references('uuid') // permission id
same recommendation here as well - the fk references will need to be updated as well

2025-01-12 20:48 UTC, kdebrecht commented on database/migrations/2024_07_10_013407_create_permission_tables.php
> +                ->references('uuid') // permission id
same recommendation here as well - the fk references will need to be updated as well

2025-01-12 20:48 UTC, kdebrecht commented on database/migrations/2024_07_10_013407_create_permission_tables.php
> +                ->references('uuid') // role id
same recommendation here as well - the fk references will need to be updated as well

2025-01-12 20:48 UTC, kdebrecht commented on app/Models/Permission.php
> +    protected $primaryKey = 'uuid';
see migration recommendations

2025-01-12 20:48 UTC, kdebrecht commented on app/Models/Role.php
> +    protected $primaryKey = 'uuid';
see migration recommendations for this model

2025-01-12 20:48 UTC, kdebrecht commented on resources/js/hooks/permissions.ts
> +export function usePermission(user: User) {
another way to get page props using inertia is to use the usePage() hook and would remove the required user param, but could be optional if you were checking another user (not authenticated) here is what that would look like

```typescript
export function usePermission(user?: User) {

  // Use the inertia use page hook to get the props from the HandleInertiaRequest Middleware
  user ??= usePage().props.auth.user;

  const hasRole = (role: string) => {
    return user?.roles?.includes(role) ?? false;
  }

  const hasPermission = (permission: string) => {
    return user?.permissions?.includes(permission) ?? false;
  }

  return { hasRole, hasPermission }
}
```

2025-01-12 20:48 UTC, kdebrecht commented on resources/js/types/index.d.ts
> +    users: User[];
is the list of users being sent in every request?  

This would probably make more sense on the ShowUsers page.. I will double check that component.

The PageProps is typically inherited by page components and the items here are expected to be in every request

2025-01-12 20:48 UTC, kdebrecht commented on resources/js/Pages/Users/List.tsx
> +
From the comment I left on the PageProps in the types definition at the end of this review

```typescript
interface ListUserPageProps extends PageProps {
  users: User[];
}
```

```typescript
export default function List({ auth, users }: ListUserPageProps) {

```


One quick thought, since we theoretically have several list pages, it may be useful to be more specific in the filename /Users/UserList or something similar.  Redundant when looking at the directory tree, but when doing a symbol or file search, this comes in handy because some places in the ui does not show the full path, just the filename.  

This has saved me some headaches in the past - just a suggesetion

2025-01-15 02:24 UTC, ntoombs19 commented on resources/js/types/index.d.ts
> +    users: User[];
It's not being sent on every request. I created a new type to use for the `List.tsx` component.

2025-01-18 16:49 UTC, glitchedmob approved these changes

2025-01-18 19:24 UTC, merged